import type { PromptCoachReport } from "../core/types.js";

export function renderPromptCoachReport(report: PromptCoachReport): string {
  const shortRewrite = report.shortRewriteInYourVoice?.trim() || report.rewriteInYourVoice;
  if (report.language === "ko") {
    return [
      "# re-prompt 코치",
      "",
      report.analysis ? `분석: requested ${report.analysis.requestedEngine}, used ${report.analysis.usedEngine}${report.analysis.fallback ? " (fallback)" : ""}` : "",
      report.analysis?.fallbackReason ? `참고: ${report.analysis.fallbackReason}` : "",
      "",
      "## 내 판단은 이거예요",
      "",
      report.oneLineTake,
      "",
      "## 네가 실제로 이렇게 말했어요",
      "",
      report.whatYouActuallyWrote,
      "",
      "## 여기서 애매했던 건 이 부분이에요",
      "",
      report.whereItWentWrong,
      "",
      "## 다음엔 이렇게 말하면 돼요",
      "",
      "```txt",
      shortRewrite,
      "```",
      "",
      "## 조금 더 탄탄하게 쓰면",
      "",
      "```txt",
      report.rewriteInYourVoice,
      "```",
      "",
      "## 왜 이게 더 좋은지",
      "",
      report.whyThisWorks,
      "",
      "## 중간에 끊고 싶으면 이 한 문장",
      "",
      "```txt",
      report.rescueLine,
      "```",
      "",
      "## 한계",
      "",
      ...report.limitations.map((item) => `- ${item}`),
      ""
    ]
      .filter((line, index, lines) => !(line === "" && lines[index - 1] === ""))
      .join("\n");
  }

  return [
    "# re-prompt coach",
    "",
    report.analysis ? `Analysis: requested ${report.analysis.requestedEngine}, used ${report.analysis.usedEngine}${report.analysis.fallback ? " (fallback)" : ""}` : "",
    report.analysis?.fallbackReason ? `Note: ${report.analysis.fallbackReason}` : "",
    "",
    "## My take",
    "",
    report.oneLineTake,
    "",
    "## What you actually wrote",
    "",
    report.whatYouActuallyWrote,
    "",
    "## Where the wording got in the way",
    "",
    report.whereItWentWrong,
    "",
    "## Say this next time",
    "",
    "```txt",
    shortRewrite,
    "```",
    "",
    "## If you want the fuller version",
    "",
    "```txt",
    report.rewriteInYourVoice,
    "```",
    "",
    "## Why this works",
    "",
    report.whyThisWorks,
    "",
    "## Rescue line for next time",
    "",
    "```txt",
    report.rescueLine,
    "```",
    "",
    "## Limitations",
    "",
    ...report.limitations.map((item) => `- ${item}`),
    ""
  ]
    .filter((line, index, lines) => !(line === "" && lines[index - 1] === ""))
    .join("\n");
}
